### ISSUE TITLE
Is there any quick and easy way to run through all these benchmarks?

### ISSUE THREAD

**Issue by treeder** [softwaremill/mqperf#1]
Like a single script that will fire up clusters, run the tests, then shut them down?

**Comment by adamw** [comment]
Unfortunately no - there's another repo, https://github.com/adamw/mqperf-chef, where I have the basic chef scripts for setting up opsworks servers. But as each messaging provider has a different setup (sometimes they provide docker imags, sometimes not), it's a case-by-case thing. And I only set up each cluster once so I didn't automate this step.
