### ISSUE TITLE
specify exact prometheus image tag

### ISSUE THREAD

**Issue by nicodewet** [softwaremill/mqperf#41]
I would suggest specifying an exact tag, avoid latest. Your prometheus config breaks with prometheus 2.

Changing to this in main.yml got prometheus up:
prometheus_image_tag: v1.8.2

**Comment by adamw** [comment]
Thanks! Maybe you could create a PR? :)

**Comment by nicodewet** [comment]
All done. May have more pull requests in time ...

**Comment by adamw** [comment]
Sure, looking forward! :)
